SAMPLE_OPPORTUNITIES = [
    {
        "source_name": "City of Sacramento Innovation Grants",
        "source_url": "https://www.cityofsacramento.gov/city-manager/oied/business/innovation-and-entrepreneurship/innovation-grants.html",
        "title": "2026 Sacramento Innovation Grant Program – Category A",
        "program_type": "grant",
        "eligibility_text": "Entrepreneurship education and access programs that serve Sacramento founders and small businesses.",
        "amount_text": "$25,000; $50,000",
        "deadline_text": "",
        "description": "Designed to create a pipeline for entrepreneurs at different stages of their journey. Programs may include training, access to capital preparation, and entrepreneurship education.",
        "location_focus": "Sacramento",
        "requires_human_review": False,
        "fit_tags": ["sacramento", "innovation", "entrepreneurship"],
    },
    {
        "source_name": "CalOSBA Funding Opportunities",
        "source_url": "https://calosba.ca.gov/for-small-businesses-and-non-profits/funding-opportunities-for-small-businesses-and-nonprofits/",
        "title": "CalOSBA Funding Opportunities for Small Businesses and Nonprofits",
        "program_type": "grant",
        "eligibility_text": "Grant programs for small businesses, non-profits, and eligible community organizations that support and promote entrepreneurship.",
        "amount_text": "",
        "deadline_text": "",
        "description": "State-level funding opportunities and partner-administered programs for California business support and entrepreneurship.",
        "location_focus": "California",
        "requires_human_review": False,
        "fit_tags": ["california", "small business", "entrepreneurship"],
    },
    {
        "source_name": "SMUD Business Rebates",
        "source_url": "https://www.smud.org/Business-Solutions-and-Rebates/Business-Rebates",
        "title": "SMUD Business Rebates",
        "program_type": "incentive",
        "eligibility_text": "Business customers may qualify for incentives and financing to improve energy efficiency.",
        "amount_text": "up to 80% of project costs",
        "deadline_text": "",
        "description": "Energy efficiency incentives for business upgrades. Valuable economically, but not automatically a direct grant.",
        "location_focus": "Sacramento",
        "requires_human_review": True,
        "fit_tags": ["sacramento", "energy", "rebate"],
    },
]
